name = "Fretboards"
uuid = "ccff39cb-adf9-4117-873b-a3f804b23ebe"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]
version = "0.1.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
ArgCheck = "2"
Crayons = "4"
DocStringExtensions = "0.8"
OffsetArrays = "1"
UnPack = "1"
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
